### ISSUE TITLE
We can mention your package in the Denote manual

### ISSUE THREAD

**Issue by protesilaos** [sarcom-sar/denote-tree#1]
Hello @sarcom-sar! If you think your package is ready for widespread use, please let me know. We can mention it in the Denote manual.

**Comment by sarcom-sar** [comment]
Hello!  The basic utility it provides (visualization and visiting notes) is ready for wide-spread use.  I have my reservations about interactive parts (editing the front matter), because while it works for simple cases, it may break under more complex ones.

We can agree, that I will e-mail you about it, when I get it on MELPA.  I believe this is a good milestone, because it will be easily accessible then.

**Comment by protesilaos** [comment]
> From: sarcom-sar ***@***.***>
> Date: Mon,  9 Dec 2024 12:38:54 -0800

> [... 6 lines elided]

> We can agree, that I will e-mail you about it, when I get it on MELPA.
> I believe this is a good milestone, because it will be easily
> accessible then.

Sounds good! Good luck with everything in the meantime.

-- 
Protesilaos Stavrou
https://protesilaos.com
